"""IR 模块入口"""
from .schema import (
    ALL_BLOCK_TYPES,
    BLOCK_HEADING,
    BLOCK_PARAGRAPH,
    BLOCK_LIST,
    BLOCK_TABLE,
    BLOCK_CALLOUT,
    BLOCK_KPI_GRID,
    BLOCK_BLOCKQUOTE,
    BLOCK_EVIDENCE_CARD,
    BLOCK_HR,
    CALLOUT_TONES,
    LIST_TYPES,
    KPI_TONES,
    RELATION_TYPES,
    validate_block,
    validate_chapter_ir,
    build_document_ir,
)

__all__ = [
    "ALL_BLOCK_TYPES",
    "BLOCK_HEADING",
    "BLOCK_PARAGRAPH",
    "BLOCK_LIST",
    "BLOCK_TABLE",
    "BLOCK_CALLOUT",
    "BLOCK_KPI_GRID",
    "BLOCK_BLOCKQUOTE",
    "BLOCK_EVIDENCE_CARD",
    "BLOCK_HR",
    "CALLOUT_TONES",
    "LIST_TYPES",
    "KPI_TONES",
    "RELATION_TYPES",
    "validate_block",
    "validate_chapter_ir",
    "build_document_ir",
]
